-- Solo lectura; compara columnas/tipos/nulabilidad contra schema.prisma.
WITH expected(table_name,column_name,data_type,is_nullable) AS (VALUES
('DicCategoria','cod','text','NO'),
('DicCategoria','nombre','text','NO'),
('DicTipo','cod','text','NO'),
('DicTipo','nombre','text','NO'),
('DicClasif','cod','text','NO'),
('DicClasif','nombre','text','NO'),
('Maestro','sku','text','NO'),
('Maestro','descripcion','text','NO'),
('Maestro','categoria_cod','text','NO'),
('Maestro','tipo_cod','text','NO'),
('Maestro','clasif_cod','text','NO'),
('Campania','id','integer','NO'),
('Campania','nombre','text','NO'),
('Campania','inicia','timestamp without time zone','NO'),
('Campania','termina','timestamp without time zone','NO'),
('Campania','categoria_objetivo_cod','text','YES'),
('Campania','tipo_objetivo_cod','text','YES'),
('Campania','clasif_objetivo_cod','text','YES'),
('Campania','activa','boolean','NO'),
('Campania','activatedOnce','boolean','NO'),
('CampaniaMaestro','campaniaId','integer','NO'),
('CampaniaMaestro','sku','text','NO'),
('CampaniaMaestro','descripcion','text','NO'),
('CampaniaMaestro','categoria_cod','text','NO'),
('CampaniaMaestro','tipo_cod','text','NO'),
('CampaniaMaestro','clasif_cod','text','NO'),
('Escaneo','id','integer','NO'),
('Escaneo','ts','timestamp without time zone','NO'),
('Escaneo','campaniaId','integer','NO'),
('Escaneo','sucursal','text','NO'),
('Escaneo','email','text','NO'),
('Escaneo','sku','text','NO'),
('Escaneo','skuRaw','text','YES'),
('Escaneo','skuNormalized','text','YES'),
('Escaneo','idempotencyKey','text','YES'),
('Escaneo','estado','text','NO'),
('Escaneo','categoria_sug_cod','text','YES'),
('Escaneo','tipo_sug_cod','text','YES'),
('Escaneo','clasif_sug_cod','text','YES'),
('Escaneo','asum_categoria_cod','text','YES'),
('Escaneo','asum_tipo_cod','text','YES'),
('Escaneo','asum_clasif_cod','text','YES'),
('Actualizacion','id','integer','NO'),
('Actualizacion','ts','timestamp without time zone','NO'),
('Actualizacion','campaniaId','integer','NO'),
('Actualizacion','sku','text','NO'),
('Actualizacion','old_categoria_cod','text','YES'),
('Actualizacion','old_tipo_cod','text','YES'),
('Actualizacion','old_clasif_cod','text','YES'),
('Actualizacion','new_categoria_cod','text','NO'),
('Actualizacion','new_tipo_cod','text','NO'),
('Actualizacion','new_clasif_cod','text','NO'),
('Actualizacion','estado','text','NO'),
('Actualizacion','decidedBy','text','YES'),
('Actualizacion','decidedAt','timestamp without time zone','YES'),
('Actualizacion','notas','text','YES'),
('Actualizacion','archivada','boolean','NO'),
('Actualizacion','archivadaBy','text','YES'),
('Actualizacion','archivadaAt','timestamp without time zone','YES'),
('Actualizacion','appliedAt','timestamp without time zone','YES'),
('Actualizacion','exported_categoria_at','timestamp without time zone','YES'),
('Actualizacion','exported_tipo_at','timestamp without time zone','YES'),
('Actualizacion','exported_clasif_at','timestamp without time zone','YES'),
('SkuStage','campaniaId','integer','NO'),
('SkuStage','sku','text','NO'),
('SkuStage','stage','text','NO'),
('SkuStage','updatedBy','text','YES'),
('SkuStage','updatedAt','timestamp without time zone','NO'),
('UnknownSku','id','integer','NO'),
('UnknownSku','campaniaId','integer','NO'),
('UnknownSku','sku','text','NO'),
('UnknownSku','skuRaw','text','YES'),
('UnknownSku','skuNormalized','text','YES'),
('UnknownSku','descripcion','text','YES'),
('UnknownSku','categoria_cod','text','YES'),
('UnknownSku','tipo_cod','text','YES'),
('UnknownSku','clasif_cod','text','YES'),
('UnknownSku','status','text','YES'),
('UnknownSku','seenCount','integer','NO'),
('UnknownSku','firstSeenAt','timestamp without time zone','YES'),
('UnknownSku','lastSeenAt','timestamp without time zone','YES'),
('UnknownSku','mergedIntoSku','text','YES'),
('UnknownSku','decidedBy','text','YES'),
('UnknownSku','decidedAt','timestamp without time zone','YES'),
('UnknownSku','decisionReason','text','YES'),
('UnknownSku','appliedToMaestroAt','timestamp without time zone','YES'),
('UnknownSku','appliedToMaestroBy','text','YES'),
('UnknownSku','updatedBy','text','YES'),
('UnknownSku','createdAt','timestamp without time zone','NO'),
('UnknownSku','updatedAt','timestamp without time zone','NO')
), actual AS (
 SELECT table_name,column_name,data_type,is_nullable FROM information_schema.columns
 WHERE table_schema='public'
), missing_or_different AS (SELECT * FROM expected EXCEPT SELECT * FROM actual),
unexpected AS (SELECT * FROM actual EXCEPT SELECT * FROM expected)
SELECT (SELECT count(*) FROM expected) AS expected_columns,
 (SELECT count(*) FROM actual) AS actual_columns,
 (SELECT count(*) FROM missing_or_different) AS missing_or_different,
 (SELECT count(*) FROM unexpected) AS unexpected,
 (SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE') AS tables,
 (SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname='public' AND c.contype='p') AS primary_keys,
 (SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname='public' AND c.contype='f') AS foreign_keys;
